### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by CavalcanteLeo** [Vyoam/InsomniaToPostmanFormat#1]
Any documentation to see how to get things to work here?

**Comment by Vyoam** [comment]
Most of it is covered in ReadMe. https://github.com/Vyoam/InsomniaToPostmanFormat/blob/main/README.md

Main points...
* Runs with NodeJS: `node convertJsonFile.js`
* Input and output file name hardcoded (you can update the last lines)

Will try to enhance it this weekend.

**Comment by Vyoam** [comment]
ReadMe is fairly descriptive now. Closing.
