### ISSUE TITLE
URLs in request are appended with 'http://' 

### ISSUE THREAD

**Issue by bacteriostat** [Vyoam/InsomniaToPostmanFormat#3]
Thanks for the script! 

I have saved part of request URL as variable in Insomnia and the final URL looks like this:

> `host`/customer/`customer_id`

where `host` is a variable.

After conversion the URL in postman becomes like this:

> http://`host`/customer/`customer_id`

which breaks the request because variable `host` already has https in it.

**Comment by Vyoam** [comment]
Thanks for bringing this up. Will try to go over it this week/weekend.

For note, there's this line in the code...
urlParts[0] = 'http';
I think it's there so that any request lacking protocol gets http by default. I'm not sure anymore whether it's even needed.

**Comment by Vyoam** [comment]
Pushed the fix. Should be good now. Now, even if a protocol isn't detected, the script avoids adding a 'default' protocol. Postman seems smart enough to do it on its own.
