### ISSUE TITLE
Does this handle (or bail) on different Insomnia versions

### ISSUE THREAD

**Issue by dimitropoulos** [Vyoam/InsomniaToPostmanFormat#4]
Hi!

Thanks for making this tool!

From looking at the code it doesn't check the version of the insomnia export.  To date there have been 4 versions (you can see types for them here: https://github.com/Kong/insomnia/tree/develop/packages/insomnia-importers/src/importers).

If nothing else, it seems ideal for you to exit early if `__export_format` is anything _other than_ `4` for now, maybe?

**Comment by Vyoam** [comment]
Thanks @dimitropoulos for identifying this. Early exit seems good. Will take care of it this weekend.

That does bring another question to mind...
I'm working on direct integration with insomnia: https://github.com/Vyoam/insomnia/commits/feature/postman-export . And I believe you are from the core team.
My hunch is, if the insomnia team changes the the request interface, workspace interface etc., this export functionality can break in future. We'll probably discuss more when I raise the PR, but do let me know if you have any initial thoughts on this.

**Comment by dimitropoulos** [comment]
Yep: exactly.  That's why I wanted to mention the version.  I am on the core team, yeah.  For what it's worth (at least as far as I'm aware, I hope I'm not wrong) I think we would welcome a PR in Insomnia for _exporting_ to Postman (straight from Insomnia itself).  That completely gets us around needing to worry about formats because we aren't (then) exporting from one format to another, but rather a database state within Insomnia to a flat file.  We have the workings to do this with 3 formats already (Insomnia json, Insomnia yaml, and HAR), we could add a 4th (Postman 2.1.0).

Vendor lock-in is not how Kong (who owns/operates Insomnia) generally rolls.  We want our users to have freedom of choice and I think that extends to insomnia exporting to postman.

**Comment by Vyoam** [comment]
I have added the version check and early exit.

Unfortunately I didn't get time to finish up the PR for the official insomnia repo this week. Will try to resume ASAP and revisit the repercussions of the version issue in that.
